name: Holiday

on:
  watch:
    types: [started]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: gem install holiday_jp
    - name: Run
      id: script
      run: ruby -r holiday_jp -e 'if false ;exit(1);end;exit(0)'
    - name: echo
      run: echo 'Hello'
      if: ${{ steps.script.outcome }}

