name: Holiday

on:
  watch:
    types: [started]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: gem install holiday_jp
    - name: Holiday Judgment
      id: holiday-judge
      run: |
        echo "::set-output name=result::$(ruby -r holiday_jp -e 'p !!HolidayJp.holiday?(Date.today')"
    - name: echo
      run: echo 'Hello'
      if: ${{ steps.holiday-judge.outputs.result == false }}
